server:
  port: 8443
  ssl:
    key-store: classpath:iabdokeystore.jks
    key-store-password: Average1
    keyStoreType: jks
    keyAlias: iabdo
security:
  oauth2:
    client:
      #clientId: 233668646673605
      #clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
      clientId: 1990922091019159
      clientSecret: 84a6b816305c2658f45ced45db6ab8ab      
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth?redirect_url=https://localhost:8443/
      #tokenName: oauth_token
      tokenName: access_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      registered-redirect-uri: https://localhost:8443/
      pre-established-redirect-uri: https://localhost:8443/
    resource:
      userInfoUri: https://graph.facebook.com/me
logging:
  level:
    org.springframework.security: DEBUG      

#spring:
#  security:
#    oauth2:
#      client:
#        registration: (1)
#          adfs:   (2)
#            client-id: your-app-client-id
#            scope: openid
#            redirect-uri: your-base-url/login/oauth2/code/adfs
#            client-authentication-method: basic
#            authorization-grant-type: authorization_code
#        provider: (3)
#          adfs:
#            authorization-uri: https://your-adfs-domain/adfs/oauth2/authorize
#            token-uri: https://your-adfs-domain/adfs/oauth2/token
#            user-info-authentication-method: query
#            jwk-set-uri: https://your-adfs-domain/adfs/discovery/keys
#            user-name-attribute: upn